### ISSUE TITLE
Scavenge failed (?)

### ISSUE THREAD

**Issue by rickardoberg** [EventStore/EventStore#1039]
I ran scavenge on one instance in a cluster, and on that particular machine it seems to have worked. Another instance get this in the error log though:

`[PID:01251:030 2016.09.02 04:19:08.425 ERROR StorageScavenger    ] Failed to write the $scavengeIndexInitialized event to the $scavenges stream. Reason: WrongExpectedVersion
[PID:01251:030 2016.09.02 04:19:10.449 ERROR StorageScavenger    ] Failed to write the $maxAge of 30 days metadata for the $scavenges stream. Reason: CommitTimeout
`

What did I do wrong, is it fixable? 

(EventStore 3.4)

**Comment by hayley-jean** [comment]
The error messages that you are seeing  in the logs are nothing to worry about

The first `WrongExpectedVersion` error is thrown because that event was created on a previous run of Event Store. That message is no longer logged in the latest release (3.9.0)

The second `CommitTimeout` error message is letting you know that the maxAge metadata wasn't written to the scavenges stream. This shouldn't cause any issues - that metadata will be set when you next start Event Store, and all it does is delete any scavenge history older than 30 days.

Also, if you want to scavenge your whole cluster, you will need to start a scavenge on each node in your cluster. The scavenge only runs on the node on which it was started.
