### ISSUE TITLE
Introduce memory mapped indexes

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#1350]
1. Look at introducing memory mapped files for indexes
2. Investigate whether we still need to cache the midpoints if we are using memory mapped indexes
3. Provide an option to disable the verification of indexes, there is an option to disable verification of chunks.

This will improve Event Store startup times of much larger Event Store indexes.

**Comment by pgermishuys** [comment]
There is a `wip` branch over here for anyone who is keen to get started on this. https://github.com/EventStore/EventStore/tree/index-mmap.

**Comment by gregoryyoung** [comment]
The midpoint cache is most likely still wanted on large index files. Without it there is a possibility of requiring many disk reads in order to reach a record. For smaller indexes it is likely fine and you would just pay a "warm up penalty". You could immediately start using the index and eventually it will come into memory.

**Comment by gregoryyoung** [comment]
Put more simply, we know more about which pages should be in memory than the OS does on very large indexes (think 10TB database where you might have a 250gb index)

**Comment by oskardudycz** [comment]
In the last three years, there was a lot of work going on around indexes, so this issue might be obsolete. There are plans to do another overhaul, but let's tackle that in a dedicated issue.
