### ISSUE TITLE
Missing first Event when using Category ("$ce-") Projection

### ISSUE THREAD

**Issue by ThomasBoettcherHolschen** [EventStore/EventStore#1475]
Here is a litte sample Program that tries to insert two events in one stream and than subscribe to them in an empty eventstore using the category-projection. [GIST](https://gist.github.com/ThomasBoettcherHolschen/9a3d39bc8266316e781fd1d0e4a8309d)

The output of this little program is:

> Event written with NextExpectedVersion: 0, on LogPosition: 43926/43926. Data : Test1
> Event written with NextExpectedVersion: 1, on LogPosition: 45587/45587. Data : Test2
> Received: ThisIsACategory-Teststream:1 with data :Test2

What I was expecting to see is :

> Event written with NextExpectedVersion: 0, on LogPosition: 43926/43926. Data : Test1
> Event written with NextExpectedVersion: 1, on LogPosition: 45587/45587. Data : Test2
> **Received: ThisIsACategory-Teststream:0 with data :Test1**
> Received: ThisIsACategory-Teststream:1 with data :Test2

because I've subscribed to the stream with  ` StreamPosition.Start`

I'm using EventStore 4.0.3 with C# Client 4.0.3 on Windows 10.
Eventstore is started using 
`EventStore.ClusterNode.exe --config=config.yml` 

config.yml contains
`Db:                         C:\Dev\Data\EventStore\db`
`Log:                        C:\Dev\Data\EventStore\logs`
`StartStandardProjections:   TRUE`
`RunProjections:             ALL`

What am I doing wrong?

**Comment by hayley-jean** [comment]
Hi @ThomasBoettcherHolschen 

The start of a catchup subscription is exclusive, that means that when you start a catchup subscription, it will start reading from after the event number that was provided to it.

`StreamPosition.Start` translates to event number 0, which is why the first event is skipped.
You should instead use either `null` or `StreamCheckpoint.StreamStart` as the last checkpoint if you are wanting to start a catchup subscription at the very beginning of a stream.

**Comment by ThomasBoettcherHolschen** [comment]
Hi,
Works!

Thanks for the Help!
