### ISSUE TITLE
Custom projection stuck in Starting/StateLoaded or Stopping state

### ISSUE THREAD

**Issue by jwalls89** [EventStore/EventStore#1524]
Hi,

Having an issue with a custom projection that has been working for weeks on a test event store instance where the projection was at -1.0% and stopping the projection resulted in hanging stopping.  

We've seen this behavior before with older versions of event store and usually triggering a cluster election sorts this out.  In this case it isn't sorting it out.  We've tried stopping the cluster completely and restarting at which point the projection gets stuck in Starting/StateLoaded status.  

Effectively we have a projection that is in a zombie state and don't see to be able to do anything with it at all.   Looking through the logs there are no errors at the time the projection last filed a statistic report but statistics reports appear to stop for a day.

How do we force a projection to stop so we can reset it?

ES: 4.0.3.  Logs available on request

**Comment by hayley-jean** [comment]
Hi @jwalls89 

There has been a fix for a similar issue in PR #1460.
We will be releasing an RC for 4.0.4 within the next few days. Could you test with this version when it is released and see if that corrects the issue?

If you can provide us with your logs, we can also check if it's the same issue or a new one.
You can email them to hayley at geteventstore.com if you would rather not attach them here.

**Comment by oceanexplorer** [comment]
We have upgraded to 4.1.0 and we are still having the same issue with the projection getting stuck in a stopping state. Shall I provide you with the logs?

**Comment by hayley-jean** [comment]
Yes please @oceanexplorer
You can send the logs to hayley at geteventstore.com if you would prefer not to share them here.

**Comment by oceanexplorer** [comment]
Hayley, as discussed in email here is the definition for the transaction-progress-monitor in case it gets stripped out of the email.
[transaction_progress_monitor.zip](https://github.com/EventStore/EventStore/files/1710865/transaction_progress_monitor.zip)

**Comment by hayley-jean** [comment]
Thank you for the help @oceanexplorer 

Your projection is stalling because the streams that the projection was reading from have been deleted.
This causes the checkpoint manager of the projection to throw an error, but it does not fault the projection. This results in the projection stalling.
As far as we are aware, this is only an issue with projections using the `fromStream` selector.

As a work around until we can fix this issue, you can stop the projection before deleting these streams, and reset it afterwards.

**Comment by hayley-jean** [comment]
I believe that the issue with deleted streams should have been fixed with PR https://github.com/EventStore/EventStore/pull/2447, as well as a number of other fixes to projections.

@oceanexplorer or @jwalls89, have either of you seen this issue in later versions of Event Store (i.e. >5.0.8, 20.10 or 21.10)?

**Comment by oceanexplorer** [comment]
I’m afraid that I and (@jwalls89) are no longer working on the project that utilised EventStore so are I can’t provide any feedback on this issue. Sorry.

**Comment by hayley-jean** [comment]
No problem, thanks for letting me know
I'll go ahead and close this issue then, if anyone sees this problem again please open a new issue on this repo
