### ISSUE TITLE
TCP stats API call not working correctly

### ISSUE THREAD

**Issue by prolic** [EventStore/EventStore#1590]
calling `GET /stats/tcp` returns an empty array, but calling `GET /stats` includes tcp stats as expected.

tested on EventStore-OSS-Ubuntu-14.04-v4.1.0

**Comment by shaan1337** [comment]
@prolic the correct call to obtain the TCP stats is by doing :  `GET /stats/proc/tcp`

The stats endpoint stores stats as a tree structure, so you can obtain similar stats for other sections/sub sections by appending the full node path to the request: e.g. `GET /stats/es/queue/mainQueue`

**Comment by prolic** [comment]
thanks @shaan1337. Please note your docs are wrong then, see https://eventstore.org/docs/http-api/swagger/Stats/Get%20TCP%20connection%20stats.html

**Comment by shaan1337** [comment]
Hi @prolic 

Please have a look at:
https://github.com/EventStore/docs.geteventstore.com/issues/261

`/stats/tcp` and `/stats/proc/tcp` are two different endpoints
`stats/tcp` actually returns the current **active TCP connections** to the eventstore, so that's the reason you were getting an empty array.

**Comment by prolic** [comment]
@shaan1337 thanks :+1:
