### ISSUE TITLE
Specifying no limit to how quickly checkpoints can be written for a persistent subscription

### ISSUE THREAD

**Issue by sadegr** [EventStore/EventStore#1696]
Projections have a config setting called Checkpoint After Ms. According to the [documentation](https://eventstore.org/docs/projections/projections-config/index.html#checkpoint-after-ms): 
> By default, this is set to 0 seconds, which means there is no limit to how quickly checkpoints can be written.

Persistent subscriptions have a similar setting which can be set using the method `CheckPointAfter(TimeSpan time)` (see [Competing Consumers#Persistent Subscription Settings
](https://eventstore.org/docs/dotnet-api/competing-consumers/index.html#persistent-subscription-settings)). My expectation was that setting this setting to 0 for a persistent subscription would have the same effect as setting the Checkpoint After Ms setting to 0 for a projection, i.e. there is no limit to how quickly checkpoints can be written.

However, you are unable to set this setting to 0 due to the following line of code, which is called when setting both `CheckPointAfter` and `WithMessageTimeoutOf` for a persistent subscription:
https://github.com/EventStore/EventStore/blob/9dfeba531d0f8369700c98844990d8b93559bc55/src/EventStore.Core/Services/PersistentSubscription/PersistentSubscriptionService.cs#L811-L814

This is preventing these settings from being able to be set to 0 via either the UI or the HTTP API. I have not tried setting them via the .NET API but I would imagine that the above method `ToTimeout` gets called when changing these settings regardless of the client.

How do I represent "no limit to how quickly checkpoints can be written" for a persistent subscription, if not by setting `CheckPointAfter` to 0?

Side note - interestingly, because the `ToTimeout` method only checks for 0s and not negative values, you **are** able to set CheckPointAfter to negative values, although I'm not sure what the effect of doing so would be.

**Comment by arwinneil** [comment]
Hello,

`CheckPointAfter` in Persistent Subscription and `CheckPointAfterMs` in Projections have different behaviors by design. Due to internal complexities to how persistent subscriptions work, it is not possible for `CheckPointAfter` to behave like `CheckPointAfterMs` without potentially breaking functionality for users.

In theory, to the checkpointing without any time limits whatsoever in Persistent Subscriptions would mean checkpointing on every events received and acknowledged by the client, and this behavior can be achieved by setting `MaximumToCheckPoint `to 1.
