### ISSUE TITLE
.Net Core Support

### ISSUE THREAD

**Issue by lefig** [EventStore/EventStore#1715]
Hi all,

This isn't an issue but rather an expression of thanks for an excellent piece of work and a query.

I started to migrate over to .net core client and was wondering whether its possible to target .Core when building the full stack and if so whether this would be advisable.

Thanks

Fig

**Comment by jen20** [comment]
Hi @lefig! Thanks for opening an issue here, and thanks for the positive feedback. We have an internal project to port everything over to .NET Core. I posted about it in another thread, but decided to open an umbrella thread at #1716 covering the work, which we will update as it progresses. I'll go ahead and close this issue now so that there is one place to track all of this work. Please feel free to jump over to #1716 if you have further questions/comments on it!
