### ISSUE TITLE
Eventstore restart unexpected GUI behavior

### ISSUE THREAD

**Issue by ppumkin** [EventStore/EventStore#1739]
After a few months of running ES something went wrong yesterday and I had to manually restart the service. It is unclear why ES stopped accepting connection.

**Issue**
Cannot log in on the webgui for extended period of time

ON Linux box
* `sudo service eventstore status`
* `ReadIndex Rebuilding: processed 752708 records (74.2%).` was showing on the status. 

As long as the reindex is in progress when you click login nothing happens on the front end.

* `/var/lib/eventstore` is +- 5 GB in size running on azure VM
* Azure Instance was maxing out at 800/s (operations a second) during restart 
* took 16 minutes to reindex

**Expected**
Some expected front end behavior
* On the GUI show the current state of reindex?
* Blank out login button with a message?
* Faster reindexing for such a small amount of test data? (possibly caused by VM restrictions)

**Comment by shaan1337** [comment]
@ppumkin this looks related to the following fix: https://github.com/EventStore/EventStore/pull/1829 which has been merged in 5.0.0.

A partial index rebuild (up to 1M events - which is normal behaviour on startup) should not take a lot of time (up to ~15 seconds)
A full index rebuild on the other hand can take several minutes or even hours.

I'm keeping the issue open since there are other aspects mentioned regarding updating the UI with a status message when EventStore is not yet ready to handle connections.
