### ISSUE TITLE
Closed to integration testing

### ISSUE THREAD

**Issue by ppumkin** [EventStore/EventStore#1741]
I have been trying to do some integration tests on my project and I keep running into closures preventing me from creating substitutes.

I am not using Mocking frameworks because I want to feed data into my existing application and test integration of flow with specific use cases, not just surface area testing. 

- Interface `IResolvedEvent`  of `ResolvedEvent`  is Internal? Why do you hide the Interface? I could jsut use this easily... 
- `ResolvedEvent` is a struct - great I can just pass the struct in instead... but to do that I need to use Activator with Private flags making my integration testing allot harder to write. 
- Did not look further because it seems two steps is one step to many for trying to write a test

As I am vaguely familiar with the internal working of EventStore and only looked at the surface area of types uses, how would you suggest I create Substitute `ResolvedEvents` to which I can feed into my application?

**Comment by jageall** [comment]
IResolvedEvent is internal because it was added to support persistent projection retry counts and only that and I didn't want to change the surface area of the API more than the scope of the feature I was adding. Before that it didn't exist partially because … you shouldn't be depending on that everywhere in your code :)
