### ISSUE TITLE
FailOnNoServerResponse does not fail on no server response

### ISSUE THREAD

**Issue by riccardone** [EventStore/EventStore#1767]
When I set the option 'FailOnNoServerResponse' combined with 'KeepReconnecting' the operation hang indefinitely while the connection keep reconnecting

**Comment by Salgat** [comment]
One possible solution is when this setting is true, on each reconnect failure, increment the operation attempt of all queued user related operations until it hits the max operation retries and throws an exception to the user.

Our use for needing this is to gracefully degrade our service while EventStore is unavailable, so that we can still run the service in a limited form for availability reasons. Since EventStore ClientAPI doesn't support cancellation tokens or failing operations while reconnecting, we have a rather hacky way of dealing with this currently.
