### ISSUE TITLE
Can submit multiple events of the same ID when expected version is correct

### ISSUE THREAD

**Issue by waggy55** [EventStore/EventStore#1898]
Hi,

I'm not sure if this is expected behaviour, but it doesn't feel right.

If I post an event with the same ID as a previous event, I get a 201 (created) response and the event is **not** added to the stream - so far so good.

However, if I post the same event again (with the same ID), but I specify a correct expected version, the event does get added to the stream. I expected that although the expected version is correct, the event should not get added to the stream because the ID is a duplicate.

**Recreation steps**
1.
**Request:** _curl.exe -i -d "[{'eventId':'2e98b833-4964-21e9-8646-d663bd873da0', 'eventType':'AnEvent', 'data':{'a': '2'}, 'metadata':'
3'}]" "http://127.0.0.1:2113/streams/stream0" -H "Content-Type:application/vnd.eventstore.events+json"_

**Response:** 201 Created + Event added to stream

2.
**Request:** _curl.exe -i -d "[{'eventId':'2e98b833-4964-21e9-8646-d663bd873da0', 'eventType':'AnEvent', 'data':{'a': '2'}, 'metadata':'
3'}]" "http://127.0.0.1:2113/streams/stream0" -H "Content-Type:application/vnd.eventstore.events+json"_

**Response:** 201 Created + Event **not** added to stream

3.
**Request:** _curl.exe -i -d "[{'eventId':'2e98b833-4964-21e9-8646-d663bd873da0', 'eventType':'AnEvent', 'data':{'a': '2'}, 'metadata':'
3'}]" "http://127.0.0.1:2113/streams/stream0" -H "Content-Type:application/vnd.eventstore.events+json" -H "ES-ExpectedVersion:12"_

**Response:** 201 Created + Event **is** added to stream despite having a duplicate ID

Thanks,
Dan

**Comment by shaan1337** [comment]
Hello @waggy55, thank you for your report.
This seems to be the correct behaviour.

The main purpose of the `Event Id` is to be able to detect idempotent writes (at-least once semantics), not to guarantee uniqueness of events. A situation can happen when a client retries writing an event (e.g. due to a timeout) while it has already been written on the server side.

The second step in the steps you provided will be treated as an idempotent write since the write is identical to the first one (this should be printed in the logs).

The third step is not an idempotent write because you have specified `ES-ExpectedVersion` to be equal to the event number of the last event in the stream meaning that you know that this event was already written. If you had specified `ES-ExpectedVersion` to be one less (i.e 11 in your case), it would have been treated as an idempotent write.

Please see this page for more details:
https://eventstore.org/docs/dotnet-api/optimistic-concurrency-and-idempotence/index.html

Feel free to reopen the issue if you have any doubts. thanks!
