### ISSUE TITLE
Not all events are being scavenged when using $maxCount: 1

### ISSUE THREAD

**Issue by daMupfel** [EventStore/EventStore#1968]
**Describe the bug**
We have a few streams that we configured with:
```
{
  "$maxCount": 1
}
```
For some of those not all events are being scavenged:
For example:
We have a stream TEST-1 that has seen 20 events. After the scavenging the following events exist: `2, 3, 20`
This is not a problem if you read the specific stream, but they do come up when reading the `$all` stream (it is not a huge issue we just did not expect this :wink:  ).

**To Reproduce**
Could not reproduce yet, only happens in our production database.

**Expected behavior**
Events being scavenged and not showing up in $all stream anymore

**EventStore details**
 - EventStore server version: 4.1.1-hotfix-1 (to be fair, this is a custom build, for more details see here: https://github.com/EventStore/EventStore/pull/1821)
 - Operating system: CoreOS (inside docker container)

Would be glad to find out if this is expected behavior or not, thanks in advance for your help :smiley:

**Comment by gregoryyoung** [comment]
This is not a bug, this is by design.

1) You can't scavenge the current open chunk
2) Even if there are some eligible for scavenge there is a cost to a scavenged chunk (a position map). If the position map costs more than the amount that would be saved it will decide not to scavenge the chunk into a bigger slower scavenged chunk :-D Remember that map requires an extra lookup!

**Comment by daMupfel** [comment]
@gregoryyoung Thanks for the clarification :+1:

**Comment by daMupfel** [comment]
Just to confirm, you mean the ALWAYS_KEEP_SCAVENGED option, correct?
