### ISSUE TITLE
Query is not updated

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore#1983]
**Describe the bug**
From [this](https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/event-store/--Pv13AhiiU/MG2YND7DBAAJ) google groups thread

"Once you run a query, make some changes to the query and run again, it invariably errors out.  This is because it hasn't updated the query text fully.  If the text is copied and the page reloaded (which is what I do) you can see the text is missing the last few edits, so I just paste and run again and it's fine."

I haven't filed a bug for it.  I'm running 5.0.0 locally so there's a chance it's been fixed?

**To Reproduce**
1. Create a query in the UI
2. Run it
3. Make changes to the query
4. Run it again

**Expected behavior**
The query runs successfully.

**Actual behavior**
The query errors out.

**Current workaround**
Copy the text and reload the page.
Paste the text in a nd run again.

**Comment by Lougarou** [comment]
Can't seem to reproduce the issue with steps above.

However, I get an error after waiting for more than 5 minutes:
**Steps to reproduce the behavior:**
Create a query in the UI
Run it
Wait for more than 5 minutes(keep tab open) <--
Make changes to the query
Run it again

When using the Query UI tab a transient projection with a MaxAge of 7200 seconds (2 minutes) is created and polled for deletion. After around 5 minutes there should be a log message 
"Transient projection "3cd5fca0-b28f-41a1-840d-f345b8e01ff4" has expired and will be deleted. Last accessed at 9/20/2019 8:14:32 AM"

After that, if you try to update or run the projection you should get something like "The query was not updated because it was not found. The query probably expired and was deleted"

If someone else can confirm the behaviour we can rule this out as not bug.

**Comment by avish0694** [comment]
Tried a reproduction on this issue but it seems to work as intended:

Steps used to reproduce the behaviour:

1. Write 100 events in StreamA and 200 events in streamB

2. Query streamA from query tab in the UI with query code:  

```fromStream("streamA")
   .when({
        $init: function() {
           return { count: 0 }
        },
        "eventType": function(state, event) {
          state.count += 1
        }
  })
```
3. The query runs successfully producing output:

Query state : 
```
State
{
  "count": 100
}
```
4. Make changes query code by changing it to query streamB: fromStream("streamB")

5. The query runs successfully producing output:

```
State
{
  "count": 200
}
```
