### ISSUE TITLE
Partial emitted projection

### ISSUE THREAD

**Issue by Zetanova** [EventStore/EventStore#2035]
**Describe the bug**
In a projection with emit enabled, not all events are emitted

**To Reproduce**
1. Unknown, mass migration

**Expected behavior**
All events should not be links and have meta and body

**Actual behavior**
Some events are missing. They are read as links to a missing stream

**Config/Logs/Screenshots**
![image](https://user-images.githubusercontent.com/1385312/67478136-c0495900-f65b-11e9-808d-d2b595d6a6a8.png)

**EventStore details**
 - EventStore server version: 5.0.2

 - Operating system: docker

**Comment by Zetanova** [comment]
I think it was the test-delete of a stream for https://github.com/EventStore/EventStore/issues/1845

Maybe i am mistaken, i read something in the eventstore docs. 
but should the event itself not be deleted/scavenged until all references to it are removed?

**Comment by jageall** [comment]
Links to events in deleted streams will still exist until the stream with the link is deleted. There are scenarios where having links to deleted events are important.

Additionally, I would recommend not prefixing your stream with $ as that is a reserved prefix.

**Comment by Zetanova** [comment]
@jageall thx, for your answer, but i still have question. 
A stream is always the only event-data owner?
If some events in a stream are deleted then all emitted events or links 
to them are unresolvable?

**Comment by mat-mcloughlin** [comment]
Only links will be unresolvable

**Comment by Zetanova** [comment]
the projection has "emit enabled" so the events should still be readable? 
That is what i believe too, but the outcome is different.

**Comment by pgermishuys** [comment]
Hi @Zetanova, I do apologize for this being so confusing.
When a projection has `emit` enabled, it gives the ability for the projection to write messages into a stream in Event Store. This could either be a link to or a brand new message.

For example, let's say I write some messages into a stream called `Foo` and I then create a projection that will write links to messages in stream `Foo` to stream `Bar`. When I read stream `Bar`, Event Store will read the links and then know that it will need to follow the link and read the original message.

If I were to delete the messages from stream `Foo`, Event Store will be unable to read the original message by following the link.

The difference between using `emit` and `linkTo` in your projection. Emit will write brand new messages rather than links.

**Comment by Zetanova** [comment]
@pgermishuys  thank you for clarifying it. 
But now i would have a followup question. 
What perfoemance and store-size effects would a emit instead of a linkTo into stream have. 
Is there some kind of deduplication or compression happening later on?
Could maybe block-storage deduplicate then the events?

**Comment by pgermishuys** [comment]
With a `linkTo` you might save in storage space. However you incur a read cost as internally we would have to follow the link to the original message and read that.

**Comment by Zetanova** [comment]
@pgermishuys thx for your answare.

It sounds off to have a 3 node cluster running on redundancy disks 
and then save all events twice on it. 

If i get some free time, i will test the performance and space coast somehow.

**Comment by mat-mcloughlin** [comment]
If there are any other questions you need answering @Zetanova please let us know
