### ISSUE TITLE
Improve the .NET clients handling of user management

### ISSUE THREAD

**Issue by mat-mcloughlin** [EventStore/EventStore#2047]
I think we can improve on the .NET Clients handling of user management. Currently to change a users password requires the following code:

```
var userManager = new UsersManager(
    new NoopLogger(), 
    new IPEndPoint(IPAddress.Loopback, 2113),
    TimeSpan.FromSeconds(30));

await userManager.ChangePasswordAsync(
    "admin", 
    "changeit", 
    "test123",
    new UserCredentials("admin", "changeit"));
```

which has a couple of unnecessary arguments and isn't very intuitive.

I think we can improve this by adding the functionality as an extension to the `IEventStoreConnection` class. Would require a little bit of thought.

Alternatively we could leave it as it is and improve it as part of the GRPC clients being worked on in #1596 

Thoughts? cc: @jageall @jen20

**Comment by wicharypawel** [comment]
Hey @mat-mcloughlin,
my two tip's for enhancement:

- please make it more intuitive that port should be 2113 which is an admin ui port. I have spend an hour trying to figure out what is the problem with my setup because I have been using 1115 (tcp tls secured). I know that after a fact it seams obvious ...

Below my code snippet for .net core & eventstore (version 5.0.5) in docker:
```
var hostInfo = Dns.GetHostEntry(configuration["EventStore:HostName"]);
var manager = new UsersManager(new ConsoleLogger(), new IPEndPoint(hostInfo.AddressList[0], int.Parse(configuration["EventStore:WebUiPort"])), TimeSpan.FromSeconds(10));
```
I think that pasting any code snippet to documentation would help a lot.

- Moreover it would be great to have information if UsersManager class is thread-safe somewhere in documentation.

Regards
Paweł

**Comment by oskardudycz** [comment]
Dear Mat, I think that's a valid suggestion, however, I don't think that we'll get to that soon, as the TCP client is legacy. I'm closing it for now.
