### ISSUE TITLE
Provide the ability for pre netcoreapp3.1 applications to leverage gRPC.

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#2165]
The Event Store gRPC Client currently targets netcoreapp3.1.  We need to investigate if there is a way we can provide a client targeting a lower dependency (netstandard 2.0) for customers to easily move to gRPC.

**Comment by jageall** [comment]
Probably the easiest way to attempt this is going to be to use the previous c implementation of gRPC from google as the dependency for lower framework targets. We should also try and support net 452 as well if we can.

**Comment by MCGPPeters** [comment]
Is this still planned for the RC? It isn't in preview 2 and it would a be very welcome addition..

**Comment by sunnyatticsoftware** [comment]
Hi All. I've just faced this limitation.

I use a class library that targets netstandard2.0 and wraps the "old" `EventStore.Client` 5.0.x.
I was having a look at this new gRPC client and I see that it just supports `netcoreapp3.1` so I cannot add a dependency from any netstandard class library to it. In my case the problem is not so much that I cannot use this gRPC client from older frameworks but the fact that I cannot use it from a netstandard class library (even from the latest netstandard2.1)

Having the gRPC client target netstandard2.1 would be ideal, unless for some reason it can only target frameworks..

**Comment by alexeyzimarev** [comment]
We support the current protocol for .NET Framework 4.8 in the latest .NET client
