### ISSUE TITLE
RemoteCertificateNameMismatch log entry is not as helpful as it could be

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#2549]
A mismatch between the requested hostname and the SANs of a TLS certificate results in:

```
node2_1  | [    1,18,17:56:08.727,ERR] Server certificate validation error: "The certificate provided by the server failed validation with the following error(s): RemoteCertificateNameMismatch (NoError)"
```

It is not straightforward to diagnose what the problematic name is - we should include it in this error message.

**Comment by kpfaulkner** [comment]
I am currently hitting against this as well (3 node cluster on Azure VMs). Have been hunting about for documentation and have resorted to going through the EventStore source but no luck yet. Is there any guidance on this?

**Comment by alexeyzimarev** [comment]
@kpfaulkner the certificate you use for the nodes should contain the IP address and/or DNS name of the node, so it matches with the gossip response (`https://<node>:<http-port>/gossip?format=json`). Also, we expect the nodes to have the same CN for the certificate (`eventstoredb-node`), otherwise, you need to set the `CertificateReservedNodeCommonName` option to the CN of your certificate.

**Comment by kpfaulkner** [comment]
Sorry if this seems a silly question... but does the single cert have all 3 (in my case 3 nodes) IPs in it, or are there 3 separate certificates each with their own IPs? I'd tried a cert with 1 of the IPs (these are internal IPs), also certs with multiple IPs. Still no luck.

Will keep trying.

**Comment by kpfaulkner** [comment]
Well, I suppose its progress.  I can confirm I can hit the gossip endpoint manually (from one machine to another)...  but when I run ES I get a never ending repeat of:

[ 5188,25,01:05:32.071,WRN] Failed authorization check for "(anonymous)" in 00:08:41.5050551 with "node/gossip : update Deny : Policy : Legacy 1 12/31/9999 11:59:59 PM +00:00 : default:denied by default:Deny, $"
[ 5188,11,01:05:32.620,INF] ELECTIONS: (V=516) TIMED OUT! (S=ElectingLeader, M=null).
[ 5188,11,01:05:32.620,INF] ELECTIONS: (V=517) SHIFT TO LEADER ELECTION.
[ 5188,11,01:05:32.620,INF] ELECTIONS: (V=517) VIEWCHANGE FROM ["Unspecified/10.1.2.101:2112", {29d30865-5643-48b9-b274-ee5c72ff9f11}].
[ 5188,44,01:05:33.013,WRN] Failed authorization check for "(anonymous)" in 00:08:42.4469598 with "node/gossip : update Deny : Policy : Legacy 1 12/31/9999 11:59:59 PM +00:00 : default:denied by default:Deny, $"
[ 5188,11,01:05:33.628,INF] ELECTIONS: (V=517) TIMED OUT! (S=ElectingLeader, M=null).
[ 5188,11,01:05:33.628,INF] ELECTIONS: (V=518) SHIFT TO LEADER ELECTION.
[ 5188,11,01:05:33.628,INF] ELECTIONS: (V=518) VIEWCHANGE FROM ["Unspecified/10.1.2.101:2112", {29d30865-5643-48b9-b274-ee5c72ff9f11}].
[ 5188,11,01:05:34.642,INF] ELECTIONS: (V=518) TIMED OUT! (S=ElectingLeader, M=null).
[ 5188,11,01:05:34.642,INF] ELECTIONS: (V=519) SHIFT TO LEADER ELECTION.
[ 5188,11,01:05:34.642,INF] ELECTIONS: (V=519) VIEWCHANGE FROM ["Unspecified/10.1.2.101:2112", {29d30865-5643-48b9-b274-ee5c72ff9f11}].


Given my original problem is gone (honestly, unsure how... I think it might have stopped when I manually installed the CA cert), I should probably create a new ticket for the above?

**Comment by alexeyzimarev** [comment]
> Sorry if this seems a silly question... but does the single cert have all 3 (in my case 3 nodes) IPs in it, or are there 3 separate certificates each with their own IPs? I'd tried a cert with 1 of the IPs (these are internal IPs), also certs with multiple IPs. Still no luck.

Both will work.

The Prometheus exporter uses the test environment with one certificate with three ip addresses: https://github.com/marcinbudny/eventstore_exporter/tree/master/test_env/20.6-cluster

My compose file generates three certificates, one per node:
https://github.com/alexeyzimarev/eventstore-docker

However, we found out that after deprecating the internal/external separation of HTTP, connecting to the cluster running in Docker compose using the gRPC client and gossip seed, it won't work. TCP works since it still has internal/external separation. Also, you can connect via the AdminUI.

The deny message you're seeing is most probably still because of the CN mismatch since we expect the CN I mentioned before. Our cert generation tool handles it properly, I use it in my compose file (second link).

**Comment by kpfaulkner** [comment]
Thanks heaps for that, will go over it this weekend. I'd expect the CN is good (was literally copy/pasted off the release notes) and have eyeballed it many times (in desperation ;) ). But I'll go back and enable TCP and give it a go.

Thanks again!

**Comment by ylorph** [comment]
This has been improved in later versions .
