### ISSUE TITLE
 I can't connect EventStore

### ISSUE THREAD

**Issue by dev-fatih-erol** [EventStore/EventStore#2616]
I get the following error when trying to connect. 
"Connection 'İnput From File Console App' was closed." [Here](https://github.com/alperhankendi/Eventstore-PubSub-Sample) repository.

**Comment by pgermishuys** [comment]
Hi @dev-fatih-erol,
Would you mind providing us with some information about which version of Event Store you are trying to connect to?

If it the latest docker container (Event Store Db 20.6.0), then the TCP interface is disabled by default and can be enabled using `--enable-external-tcp` and since you are using the older client, you will have to disable tcp tls as well with `--disable-external-tls`.

Please let us know if this works for you.

**Comment by dev-fatih-erol** [comment]
Hi, I'am using latest version EventStore.
I applied what you said.I keep getting the same error.

~ % docker run --name EventStore -it -p 2113:2113 -p 1113:1113 -e EVENTSTORE_DEV=true -e enable-external-tcp=true -e disable-external-tls=false  eventstore/eventstore

**Comment by pgermishuys** [comment]
Hi @dev-fatih-erol,
The environment variables for Event Store are in the format of `EVENTSTORE_{OPTION}` as documented [here](https://eventstore.com/docs/server/command-line-arguments/index.html).

In your case, setting up the environment should be
```
docker run --name EventStore -it -p 2113:2113 -p 1113:1113 -e EVENTSTORE_DEV=true -e EVENTSTORE_ENABLE_EXTERNAL_TCP=true -e EVENTSTORE_DISABLE_EXTERNAL_TCP_TLS=true eventstore/eventstore
```

**Comment by dev-fatih-erol** [comment]
Thank you so much, Worked now :) 👍
