### ISSUE TITLE
Stream Browser section in UI disabled.

### ISSUE THREAD

**Issue by kpfaulkner** [EventStore/EventStore#2640]
Sorry if I shouldn't post this here (as opposed to discuss.eventstore.com). I'm successfully posting events to a newly created 20.06 cluster but the "stream browser" section of the UI is still greyed out/disabled. I was thinking it was due to maybe the events not really being stored so if no events, no streams then the UI would be disabled, but have disproved that by programmatically retrieving the events.

Is this expected? If not, I'll write up more about reproducing this, but wanted to confirm first.

**Comment by pgermishuys** [comment]
Hey @kpfaulkner, no worries about opening the issue here as it might appear like a bug to end users.
With Event Store Db 20.6.x we have chosen to notify our customers of our intention to deprecate the atompub protocol and therefor it is disabled by default. The stream browser uses this protocol.

If you want to re-enable this functionality in the UI, you can enable it by setting `EnableAtomPubOverHttp` to `true`.

**Comment by kpfaulkner** [comment]
Cheers. Read about AtomPub being disabled but didn't associate it with the streambrowser. Thankyou for clarifying :)

**Comment by mastoj** [comment]
What is the recommended way to "browse" the streams, or do I have to write queries to get the data out?

**Comment by feli0821** [comment]
[pgermishuys], sorry new here.  how do i "you can enable it by setting EnableAtomPubOverHttp to true."?  thank you.
