### ISSUE TITLE
Disposing a Connection in ClientAPI notifies subscriptions with ConnectionClosed

### ISSUE THREAD

**Issue by rastrup** [EventStore/EventStore#2850]
Using 
EventStore.ClientAPI 20.10.0
net48/netstandard2.0

When we dispose of an IEventStoreConnection our subscriptions (IEventStoreConnection.SubscribeToStreamFrom) are notified of the closing of the connection through the subscriptionDropped action with reason SubscriptionDropReason.ConnectionClosed.
This should be SubscriptionDropReason.UserInitiated so not to confuse with connections dropped due to Tcp errors like for instance Heartbeat issues.

**Comment by alexeyzimarev** [comment]
Have you tried to explicitly call `Close` on the connection before disposing it?

**Comment by rastrup** [comment]
> Have you tried to explicitly call `Close` on the connection before disposing it?

Looking into the code of EventStoreNodeConnection this is the content of the Dispose method so I do not see the difference
`		void IDisposable.Dispose() {
			Close();
		}`

**Comment by oskardudycz** [comment]
Unfortunately, that's the expected behaviour. I agree that this would be good information to have while getting a drop callback, but this is something that was consistent in the old versions. For sure we cannot know if `Dispose` method was called by the application code, or just regular .NET disposal, but for Close it'd make sense. As TCP client is considered legacy, we don't plan to change it, but we're open for Pull Requests around that.

I'll close the issue for now.
