### ISSUE TITLE
Grpc allows any user action by default without any auth

### ISSUE THREAD

**Issue by astorath** [EventStore/EventStore#3031]
**Describe the bug**
`SystemRoles.All` should not include `anonymous`.

**To Reproduce**

1. Launch simple server with auth enabled (`--insecure=false`)
2. Connect without any credentials via GRPC: `esdb://localhost:2113?tls=true&TlsVerifyCert=false`
3. Write / read any stream

**Expected behavior**
Default ACL allows any authenticated user to read / write any user steam. Anonymous (Unauthenticated) users should not be able to access a stream by default.

**Actual behavior**
Default ACL allows anonymous (Unauthenticated) users to read / write any user steam.

**EventStore details**

* EventStore server version: 20.10, 21.6
* Operating system: Ubuntu-18.04

<sub>[DB-40](https://linear.app/eventstore/issue/DB-40/grpc-allows-any-user-action-by-default-without-any-auth)</sub>

**Comment by oskardudycz** [comment]
Currently, that's expected behaviour, as we recommend using HTTPS in the production environment. But I agree that we should not allow anonymous access in general. I think that's something to consider in one of the next releases, to at least make opt-in. I know that some customers (especially running Kubernetes) are using HTTP traffic behind VPC, that's quite common practice.

@hayley-jean FYI.

**Comment by timothycoleman** [comment]
The default behaviour changed in 23.6 to disallow anonymous stream access by default, I'll close this for now please feel free to reopen if you have any further problems
