### ISSUE TITLE
ES-TrustedAuth is useless with 20.+ version

### ISSUE THREAD

**Issue by astorath** [EventStore/EventStore#3032]
**Is your feature request related to a problem? Please describe.**
After introduction of GRPC with mTLS-based internode cluster authentication, `ES-TrustedAuth` header option became obsolete. If you "hide" http endpoint, cluster nodes can't authenticate via mTLS. If you publish http endpoint, anyone can authenticate via this header.

**Describe the solution you'd like**

I see a few options to handle this:
- split _trusted_ and _untrusted_ endpoints and allow forcing mTLS on _untrusted_ endpoint, while using  `ES-TrustedAuth` header on _trusted_, 
- allow specifying allowed IPs to accept `ES-TrustedAuth` header, e.g. 127.0.0.1 or balancer IP,
- force mTLS to use `ES-TrustedAuth` header (so that balancer must have cluster certificate to control authentication)

**Comment by oskardudycz** [comment]
@shaan1337 do you have some thoughts on that?

**Comment by ylorph** [comment]
Hi @astorath 
While nodes in a cluster do communicate over TLS and perform mutual authentication , 
the `ES-TrustedAuth` is _not_ about node to node communiation , it's for client to node authentication when some intermediary is doing the authentication instead of eventstore .
This header is only valid for the HTTP client<-> server protocol, not the gRPC or TCP protocol
It also need to be enabled on the server config (ENABLE TRUSTED AUTH) as this is a sceurity sensitive header.
https://developers.eventstore.com/server/v5/security/trusted-intermediary.html
