### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x8007FF06

### ISSUE THREAD

**Issue by shujahm** [EventStore/EventStore#3145]
**Describe the bug**
Running M1 Apple Silicon, and not able to run the docket image or neither install any binaries available on the internet.

Any plans soon for supporting Apple M1 anytime in future ?

**Comment by josefrnandezz** [comment]
Hi, I'm having the same issue.

**Comment by pvanbuijtene** [comment]
Relates to #2380

**Comment by oskardudycz** [comment]
@shujahm, currently, it's impossible to provide the native database build for the Apple M1 because of the issues with the gRPC and updated files API on Apple M1. Still, we provided a Docker image for the development needs: `21.10.0-alpha-arm64v8`. It is available here: https://github.com/EventStore/EventStore/pkgs/container/eventstore/11006179?tag=21.10.0-alpha-arm64v8. 

It's an alpha release but should be stable. Our internal tests haven't found any specific issues with it.

I'm closing this issue, please refer to #2380 for more questions or comments.
