### ISSUE TITLE
Docker image based on alpine

### ISSUE THREAD

**Issue by cephos** [EventStore/EventStore#3482]
Would it be possible to set up a docker-image based on alpine instead of ubuntu? I hope that a smaller Image than the current 200mb+ would be possible this way.

**Comment by oskardudycz** [comment]
Currently, alpine images are available in the GitHub Container Registry, you can check it here: https://github.com/EventStore/EventStore/pkgs/container/EventStore%2Feventstore. When all of the internal QA rounds will confirm that there are no differences to ubuntu ones (currently we haven't found issues) then we'll consider releasing it also to DockerHub.

**Comment by ylorph** [comment]
@cephos : Alpîne is not on our offically supported list of distributions.
As Oskar pointed we do have the image in github registry:
 https://github.com/EventStore/EventStore/pkgs/container/EventStore
 We do not recommend to use it in production environment.

We don't have any intention to add it to docker hub directly , because we don't offically support it.
