### ISSUE TITLE
Stop ESDB from starting when --config specified but not found

### ISSUE THREAD

**Issue by ylorph** [EventStore/EventStore#3534]
**Is your feature request related to a problem? Please describe.**
When ESDB is started with --config specified if the file is not found it starts with all defaults on.
 and stops because the default is secure and no config is found 
 `Invalid Configuration: A certificate is required unless insecure mode (--insecure) is set`

**Describe the solution you'd like**
The server should not start and tell "config file not found"
since the error given is misleading

**Describe alternatives you've considered**

**Additional context**

**Comment by jamesmintram** [comment]
I took a look at this and see that a solution is not obvious. 

By the time it comes to loading the config yaml, all of the configuration sources have been merged (Default, Command Line and Env) The Default configuration contains an entry for Config. 

So a simple "The config file does not exist" check is not enough to determine an error due to a default being present.

One approach to this would be to check if the value of Config was equal to the Default value of config, and if not - treat a missing file as an error.

Alternatively, one could build another config containing all user/environment supplied config options and use that to determine if Config had been explicitly specified.

I prefer the second option, so I'll look at creating a fix based on that - unless there are any objections? :)
