### ISSUE TITLE
Stats on mac

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#365]
[78782,53,23:49:09.904] Couldn't get free mem on linux, received memory info raw string: []
ApplicationName='free', CommandLine='-b', CurrentDirectory='', Native error= Cannot find the specified file

**Comment by gregoryyoung** [comment]
fixed.

**Comment by haf** [comment]
What commit fixes this?

**Comment by gregoryyoung** [comment]
https://github.com/EventStore/EventStore/blob/competing-etc/src/EventStore.Core/Services/Monitoring/SystemStatsHelper.cs#L204
is the code I don't know the commit off the top of my head.

On Thu, Aug 20, 2015 at 1:01 PM, Henrik Feldt <notifications@github.com>
wrote:

> What commit fixes this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/365#issuecomment-132962628>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
it hasn't been brought into release 3.2.0 yet it will likely early next week.

**Comment by gregoryyoung** [comment]
https://github.com/EventStore/EventStore/commit/65b0b6731b0ae145c5b5cb86d85a4dfc39422d98#diff-4efbc0074c07742e9fed2fc6fa53417b

**Comment by haf** [comment]
Thank you. Some background for google/you: We ran into something similar. It turned out that with about 250 MiB free on a centos with 1GiB, with ES running with 1.3 GiB memory (committed?) but only 700 MiB resident (and 20 GiB fast SSD for swap), the shell to `df -P /var/lib/eventstore` failed with a very similar error message. We found a thread on the user group stating that someone solved it by just giving the machine more memory, so we did, and that solved this particular problem.
