### ISSUE TITLE
500 when subscribing to $all stream with http api

### ISSUE THREAD

**Issue by ABZ0** [EventStore/EventStore#3665]
**Describe the bug**

**To Reproduce**

1. Connect to esdb cloud
2. request GET  {url}/subscriptions/$all/{subs-name}/{count}

**Expected behavior**
By default, reading a stream via a persistent subscription returns a single event per request and does not embed the event properties as part of the response.

**Actual behavior**
Response is empty with status 500

**Config/Logs/Screenshots**
If applicable, please attach your node configuration, logs or any screenshots.

**EventStore details**

* EventStore server version:  22.6.0.0
* Operating system:
* EventStore client version (if applicable):

**Additional context**

<sub>[DB-51](https://linear.app/eventstore/issue/DB-51/500-when-subscribing-to-dollarall-stream-with-http-api)</sub>

**Comment by hayley-jean** [comment]
Hi @ABZ0, thanks for reaching out

Persistent subscriptions to $all are only supported over gRPC using one of the gRPC clients, so it's expected that they won't work over the HTTP API.

That being said, the server should give a proper error response rather than just returning an empty error.
I also see that the warnings about this aren't being shown in the docs, so we'll check that out too.
