### ISSUE TITLE
Web UI showing data from different Instance

### ISSUE THREAD

**Issue by djowatts** [EventStore/EventStore#373]
I have two instances of Event Store running. 

When I log into the Web UI of either of the instances, the streams, events and projections for that instance are shown in the web UI for every instance, even after having cleared my browser cache. I had to browse in incognito mode or restart my machine to be able to see the correct data in the UI for the instance that was logged into second.

**Comment by gregoryyoung** [comment]
Same stream name and uri? What does curl say?

**Comment by pgermishuys** [comment]
@djowatts it seems the issue is related to the cookie stored. 

This cookie contains the server path.
https://github.com/EventStore/EventStore.UI/blob/dev/src/js/services/AuthService.js#L50

Upon navigating to the UI, it checks if the cookie exists and sets the server to what's stored in the cookie.
https://github.com/EventStore/EventStore.UI/blob/dev/src/js/run.js#L15
https://github.com/EventStore/EventStore.UI/blob/dev/src/js/services/AuthService.js#L60

**Comment by SlyNet** [comment]
This behavior confuses a lot when running multiple event store instances on the same machine
