### ISSUE TITLE
Log failed ops that will be retried as WARN or INFO rather than ERROR

### ISSUE THREAD

**Issue by eulerfx** [EventStore/EventStore#398]
I see these quite a bit logged at ERROR:

> EventStoreConnection 'ES-d68b535e-27ca-4593-aafa-fc92c90c02f1': operation never got response from server.
UTC now: 05:09:10.949, operation: Operation ReadStreamEventsForwardOperation ({11bc12a1-5f8b-446d-b637-157baf92b41d}): Stream: skus-15fa897dff5e4e5795859bf5db4dac06, FromEventNumber: 0, MaxCount: 1000, ResolveLinkTos: False, RequireMaster: False, retry count: 0, created: 05:09:03.436, last updated: 05:09:03.436.

Since these will be retried, it would be better if these were logged at a less severe level.

**Comment by jen20** [comment]
Logging overall needs more attention - overall I'm in agreement with #255 that we should switch to structured logging and away from NLog in the server to make it easier to action log entries with heka or LogStash.

Retryable operations in the client being retried is expected behaviour though, so I'm with you this, it should be `INFO`.

**Comment by gregoryyoung** [comment]
Updated client api to change this to a debug level message.
