### ISSUE TITLE
"Consumer too slow. Client resubscription required."

### ISSUE THREAD

**Issue by rickardoberg** [EventStore/EventStore#4007]
**Describe the bug**
Given we are using a subscription to maintain a read model from a stream
When we run a large import of events into the stream
Then the subscription aborts with the message "Consumer too slow. Client resubscription required."

I can't find where this timeout is set, so can't increase it. If I just resubscribe the connection aborts almost immediately with the same message. If I temporarily switch to reactive stream to catch up, and then back to subscription, it almost immediately aborts with this message.

I don't know if this is a code bug, or documentation bug (how to increase the timeout), or user bug. Part of the issue it seems is that there is no backpressure handling with subscriptions, so if onEvent takes too long (as it has to block pending read model update) it just breaks, and there's not a whole lot to be done about it.

**EventStore details**

* EventStore server version:
  eventstore/eventstore:22.10.3-buster-slim in Docker, 4GB ram and 2 CPUs assigned
* Operating system:
  Docker running in Windows 11
* EventStore client version (if applicable):
  Java client 4.3.0

<sub>[DB-462](https://linear.app/eventstore/issue/DB-462/consumer-too-slow-client-resubscription-required)</sub>

**Comment by ylorph** [comment]
related to https://discuss.eventstore.com/t/reactive-stream-api-with-catchup-semantics/4801

**Comment by ahjohannessen** [comment]
@rickardoberg Had similar issue with that thing, solved it partially by first do a read to the end and then switch to subscribe in the read model projection process code

**Comment by rickardoberg** [comment]
@ahjohannessen Yes, I tried this yesterday, and it "works". So on startup do a reactive stream, when that finishes switch to subscription. When that inevitably blows up switch to reactive stream to catch up, and so on. 

The problem is that after switching to reactive stream the read model fairly quickly catches up and then switches to subscription, which almost immediately proceeds to fail with "consumer too slow", and then back again to reactive stream. Logs fill up quickly with connect/resubscribe info/warnings for no good reason.

So does it "work"? Sure. Is this a good user experience? Nope.

I would prefer either that subscription switches to non-live mode silently, or that there was a way to get a reactive stream that doesn't end when the stream ends. Either of those would be preferable to the current state.

**Comment by ahjohannessen** [comment]
@rickardoberg I agree with you. At least we could have a way to tweak what is “slow”.

**Comment by alexeyzimarev** [comment]
We have an internal issue to handle this, we'll follow up there and improve the experience soon.

**Comment by timothycoleman** [comment]
Hi @rickardoberg @ahjohannessen just fyi we're working on this currently and tracking it here https://github.com/EventStore/EventStore/issues/4089. Once that's done then a single subscription will internally transition between live and catchup as necesary.

There was some functionality similar to this before but I removed it because it didn't always do the right thing in the corner cases. Apologies that it's taken quite a while to get back round to it.

The intention when building a read model is that you start a subscription (optionally with a checkpoint) and that's pretty much it. If the subscription drops, resubscribe with the checkpoint indicating the last event that you received. After #4089 is implemented the subscription should drop infrequently (say, if there is a network issue). There shouldn't (even now before the fix) be an advantage to you manually reading before subscribing, if there is then its possible I've missed something about the problem here (?)
