### ISSUE TITLE
Exploration development

### ISSUE THREAD

**Issue by srogovtsev** [EventStore/EventStore#483]
We are currently in the first phase of our development, which means that our storage schema (stream naming, event naming, so on) will be changed often and significantly. While working with traditional DB I could just drop all objects in the database (I am not concerned with data retention) and start anew, but as far as I understand, in EventStore system preferences are stored in same "db" as the user streams, so if I drop it, I have to re-setup users and so on.

Is there any simple way to clean all user-defined objects in EventStore db, or is there any other recommended way to do what we're trying to achieve?

**Comment by jen20** [comment]
There is no way to delete all user defined objects - the database files are immutable. The best bet here is to script the setup (bash with curl will do for most of it) and run that script when you start up.

Not sure if you're aware of the mailing list at https://groups.google.com/forum/#!forum/event-store - that's the best place for end user support rather than bugs.

**Comment by srogovtsev** [comment]
I was not, thank you!

**Comment by jen20** [comment]
You're more likely to reach a wider range of people that can help there :-)
