### ISSUE TITLE
Problem in startup scripts on Ubuntu 15.04

### ISSUE THREAD

**Issue by atrauzzi** [EventStore/EventStore#584]
Looks like they might need a nudge, I get the following when I run `sudo service eventstore start`:

```
Failed to start eventstore.service: Unit eventstore.service failed to load: No such file or directory.
```

Running `sudo eventstored` gets the server running fine, so this is probably just an upstart-ism. :)

**Comment by jen20** [comment]
This is a known issue - the packages only include upstart scripts for Ubuntu 14.04, not unit scripts for systemd. It's currently not the highest priority on the basis that no LTS version of Ubuntu currently has systemd in it, but it's clearly something we need to address and this issue is as good a place as any for that.

I think the steps for this are:

- [] decide whether we want a new component in the repo targeting `vivid` instead of `trusty` or whether we want to do some kind of systemd vs upstart detection (I'd tend towards a separate component)
- [] investigate systemd template unit scripts, as this may allow multiple instances to run on the same box easily
- [] write the unit
- [] update the packaging and release

**Comment by pgermishuys** [comment]
We have done some work around this in our build/packaging system but requires further work to finish this work. Will be done at the latest for v4.0.0.

**Comment by pgermishuys** [comment]
This has been completed as part of the work that involved refactoring the packaging/publishing scripts and more notably around the expanding of the current support OSes.
