### ISSUE TITLE
No way to package ClientAPI on OS X

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#597]
So the branch `competing-etc` _does_ compile, and I want to package it. Looked for scripts; found `scripts/nuget-clientapi/package-clientapi.ps1`, but nothing for OS X.

There needs to be a way to package this cross-platform.

**Comment by jen20** [comment]
Why? We build the client on Windows only. Open to a PR but we won't do this
internally.

>

-- 
James

**Comment by haf** [comment]
Well I don't have Windows and you haven't released any compilations, so here we are.

Who says I'm not going to PR? It's just been 2 minutes since I wrote this issue.

**Comment by haf** [comment]
Thanks for the excellent issue management and communication around this.

**Comment by hayley-jean** [comment]
We are busy cleaning up issues that have been open and inactive for a long time and which we don't think are relevant any more due to changes.
We have changed the build process for the client to use the dotnet toolchain, so if you are still experiencing problems with this please can you open a new issue.
