### ISSUE TITLE
Retrieving partition state by projection

### ISSUE THREAD

**Issue by ianbattersby** [EventStore/EventStore#699]
I thought this was supposed to work from a stream with category (partitioned)?

```
curl -i -H "Accept:application/json" "http://127.0.0.1:2114/projection/MyProjection/state?partition=19919919" -u admin:changeit -L
```

But although I get headers and 200 OK I don't get any state content displayed. Am I missing something?

**Comment by pgermishuys** [comment]
Afaik, the partition is the full stream name.

**Comment by ianbattersby** [comment]
Ah understood, we had thought - from reading Rob Ashton's blog entries - it was the actual "projection name" and not any stream it emitted into. So how do we get state for a projection that only derives state but does not emit anything into a new stream then?

http://codeofrob.com/entries/basic-projections-in-the-eventstore.html
http://codeofrob.com/entries/creating-a-projection-per-stream-in-the-eventstore.html

**Comment by pgermishuys** [comment]
Let's work through an example,

If you have a series of streams with the format of `Account-{ID}`
e.g. `Account-123, Account-456, Account-789`
and that you have the category projections enabled.

**Getting the total balance of all accounts**
If you have the following projection
```
fromAll()
.when({
    $init: function(s,e){
        return {
            balance: 0
        }
    },
    DepositMade: function(s,e){
        s.balance += parseFloat(e.body['Balance']);
        return s;
    }
})
```

You can retrieve the state via
```
curl -i http://localhost:2113/projection/total_balance_for_all_accounts/state -u admin:changeit
```

**Balance per Account**
However, if you want a balance per account, you may now want to have a projection that uses the `Account` category... but want the projection to run for each stream in the category.

```
fromCategory('Account')
.foreachStream()
.when({
    $init: function(s,e){
        return {
            balance: 0
        }
    },
    DepositMade: function(s,e){
        s.balance += parseFloat(e.body['Balance']);
        return s;
    }
})
```
Since the state is now partitioned for each stream, you will have to retrieve the state via the partition
e.g.
```
curl -i http://localhost:2113/projection/balance_per_account/state?partition=Account-1 -u admin:changeit
```

**Comment by ianbattersby** [comment]
Amazing, it was the originating partition stream name we were missing, makes total sense now. You should put this in your docs - great explanation ;-)

**Comment by ianbattersby** [comment]
Worth noting that means @robashton's examples here (http://codeofrob.com/entries/creating-a-projection-per-stream-in-the-eventstore.html) are *now* wrong then? They should say `partition=pony-rainbowdash` and not `partition=rainbowdash`?
