### ISSUE TITLE
Slash in stream name breaks Admin UI

### ISSUE THREAD

**Issue by vladkosarev** [EventStore/EventStore#804]
If you call your stream basket/1 then it shows up in the list
![image](https://cloud.githubusercontent.com/assets/1223487/13029113/befad638-d250-11e5-904c-9dbd9d64b5b9.png)
but when you try to go to it, you get an empty stream every time. Changing to basket-1 fixes this. Seems it's just a UI bug, stream did work properly in the app.

**Comment by gregoryyoung** [comment]
Looks like it just needs url encoding

**Comment by vladkosarev** [comment]
Yeap, just seems to possibly not work if stream name uses any 'special characters' that should be url encoded.

**Comment by hayley-jean** [comment]
I've done some investigation into this issue and found that only streams having slashes are having issues with this, other special characters are being url encoded. 

However, having slashes in your stream name won't just break the UI, but querying the node for such a stream over HTTP will also return errors. Because of the way we match urls for streams (eg. /streams/{streamId}/{startEventPos}) we can't tell whether you're querying for a stream id containing slashes or for a stream from a specific position. This means that even if we fix the url encoding issue in the UI, you would still run into issues with streams containing slashes - we would need to handle these cases specially.

Is this something worth supporting?

**Comment by mikeycooper** [comment]
We tried using slashes as a sort of namespace partitioning scheme in Event Store, similar to what we're doing with Raven, and ran into this issue. It was easy enough to switch to a dash for Event Store.

**Comment by vladkosarev** [comment]
I only used slashes because, like mikeycooper, we are coming from Raven so our Ids are raven ids. Since you have to have dashes in Event Store for projections grouping functionality it really makes no sense to use '/' in streams. I think that as long as naming is properly documented this won't be a big deal. Obviously UI breaking on '/' was a pretty bad first time user experience because you don't know what you are doing wrong.

**Comment by gregoryyoung** [comment]
The solution to this is to double escape the /.

**Comment by mat-mcloughlin** [comment]
Tested in the UI and this is now fixed
