### ISSUE TITLE
ClientAPI port to Node.js

### ISSUE THREAD

**Issue by nicdex** [EventStore/EventStore#850]
Hi guys,

I ported the whole ClientAPI code to Node.js. All features are implemented, code is still not considered unstable, until I finish writing a complete tests suite for each operation.

https://github.com/nicdex/eventstore-node

Please have a look and also let me know if I need to change the license or anything since code was ported. For now I'm releasing under MIT and I mention in the README that code is a port EventStore.ClientAPI.

Thanks

**Comment by gregoryyoung** [comment]
"I ported the whole ClientAPI code to Node.js. All features are
implemented, code is still not considered unstable, until I finish writing
a complete tests suite for each operation."

Do you mean not considered stable?

"Please have a look and also let me know if I need to change the license or
anything since code was ported. For now I'm releasing under MIT and I
mention in the README that code is a port EventStore.ClientAPI.
"

All is good, the original is BSD-3 and was never intended to cause
licensing issues.

We need to add to the overall list of clients as there are many new ones...


On Tue, Mar 15, 2016 at 12:34 AM, Nicolas Dextraze <notifications@github.com
> wrote:

> Hi guys,
>
> I ported the whole ClientAPI code to Node.js. All features are
> implemented, code is still not considered unstable, until I finish writing
> a complete tests suite for each operation.
>
> https://github.com/nicdex/eventstore-node
>
> Please have a look and also let me know if I need to change the license or
> anything since code was ported. For now I'm releasing under MIT and I
> mention in the README that code is a port EventStore.ClientAPI.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/850>.
>



-- 
Studying for the Turing test

**Comment by nicdex** [comment]
Yup sorry. The code is considered unstable.

**Comment by pgermishuys** [comment]
Great! thanks @nicdex.

**Comment by pgermishuys** [comment]
This has been added to the list of APIs available under this following PR. https://github.com/EventStore/docs.geteventstore.com/pull/156
